# Generated by Django 5.2.3 on 2025-07-01 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordenes', '0001_initial'),
        ('productos', '0002_remove_producto_marca_producto_marcas'),
    ]

    operations = [
        migrations.AddField(
            model_name='detalleorden',
            name='color',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.color'),
        ),
        migrations.AddField(
            model_name='detalleorden',
            name='talla',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='productos.talla'),
        ),
    ]
