# Generated by Django 5.2.3 on 2025-07-02 16:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='perfilusuario',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='perfilusuario',
            name='genero',
            field=models.CharField(blank=True, choices=[('Mujer', 'Mujer'), ('Hombre', 'Hombre'), ('Otro', 'Prefiero No Decir')], max_length=20, null=True),
        ),
    ]
