# Generated by Django 5.2.3 on 2025-06-20 03:39

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='producto',
            old_name='descripcion',
            new_name='DESCRIPCION',
        ),
        migrations.RenameField(
            model_name='producto',
            old_name='nombre',
            new_name='NOMBRE_PRODUCTO',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='id',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='producto',
            name='precio',
        ),
        migrations.AddField(
            model_name='producto',
            name='DIAS_GARANTIA',
            field=models.IntegerField(default=30),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='FECHA_PUBLICACION',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ID_CATEGORIA',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='ID_PRODUCTO',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterModelTable(
            name='producto',
            table='producto',
        ),
        migrations.AddField(
            model_name='producto',
            name='IMAGEN',
            field=models.CharField(default='productos/producto1.jpg', max_length=150),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='producto',
            name='PRECIO',
            field=models.DecimalField(decimal_places=2, default=99999, max_digits=10),
            preserve_default=False,
        ),
    ]
