# Generated by Django 5.2.3 on 2025-06-30 22:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('productos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='producto',
            name='marca',
        ),
        migrations.AddField(
            model_name='producto',
            name='marcas',
            field=models.ManyToManyField(blank=True, to='productos.marca'),
        ),
    ]
